In [ ]:
import numpy as np

prices = np.array([100, 200, 300, 400])
prices * 1.10



array([110., 220., 330., 440.])

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr + 5

array([[15, 25, 35],
       [45, 55, 65]])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]
arr[1:4]

array([20, 30, 40])

In [ ]:
sales_day1 = np.array([120, 85, 60])
sales_day2 = np.array([150, 90, 75])
total_sales = sales_day1 + sales_day2
print(total_sales)

[270 175 135]


In [ ]:
growth = ((sales_day2 - sales_day1)/sales_day1)*100
print(growth)

[25.          5.88235294 25.        ]


In [ ]:
products = ["Product A", "Product B", "Product C"]
highest_index = np.argmax(growth)
print("highest_growth:", products[highest_index])

highest_growth: Product A


In [ ]:
temps = np.array([[25, 28, 30], [22, 24, 26], [30, 32, 33], [27, 29, 31], [20, 21, 23]])
fahrenheit = temps * 9/5 + 32
print(fahrenheit)

[[77.  82.4 86. ]
 [71.6 75.2 78.8]
 [86.  89.6 91.4]
 [80.6 84.2 87.8]
 [68.  69.8 73.4]]


In [ ]:
correction = np.array([1, -1, 0])
adjusted = temps + correction
print(adjusted)

[[26 27 30]
 [23 23 26]
 [31 31 33]
 [28 28 31]
 [21 20 23]]


In [ ]:
bp = np.array([[120, 80], [135, 85], [140, 90], [110, 70], [125, 75]])
systolic = bp[:, 0]
print(systolic)

[120 135 140 110 125]


In [ ]:
highest_bp = bp[bp[:,0] > 130]
print(highest_bp)

[[135  85]
 [140  90]]


In [ ]:
bp[bp[:, 1] < 80, 1] = 80
print("updated_bp:\n", bp)

updated_bp:
 [[120  80]
 [135  85]
 [140  90]
 [110  80]
 [125  80]]


In [ ]:
yields = np.array([[2.5, 3.0, 1.0], [2.8, 3.2, 2.0], [3.1, 2.9, 2.2], [2.6, 3.1, 1.9]])
yields[1] = yields[1] + np.array([0.2, 0.3, 0.1])
print(yields)


[[2.5 3.  1. ]
 [3.  3.5 2.1]
 [3.1 2.9 2.2]
 [2.6 3.1 1.9]]


In [ ]:
yields[:, 2] = yields[:, 2] * 1.1
print(yields)

[[2.5  3.   1.1 ]
 [3.   3.5  2.31]
 [3.1  2.9  2.42]
 [2.6  3.1  2.09]]


In [ ]:
avg = np.mean(yields, axis=0)
crops = ["CROP A", "CROP B", "CROP C"]
print("highest_avg:", crops[np.argmax(avg)])

highest_avg: CROP B


In [ ]:
scores = np.array([[85, 78, 92], [88, 74, 90], [70, 65, 80], [95, 89, 96]])
top_two = scores[:2]
print(top_two)

[[85 78 92]
 [88 74 90]]


In [ ]:
math_scores = scores[:, 0]
print(math_scores)

[85 88 70 95]


In [ ]:
science_highest = scores[scores[:, 2] > 90]
print(science_highest)

[[85 78 92]
 [95 89 96]]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr[arr > 25]

array([30, 40, 50])

In [ ]:
# Scenario: Farm Crop Yield Analysis
import numpy as np

yields = np.array([[100, 200, 300, 400], [500, 600, 700, 800], [900, 500, 400, 300]])

yields_increased = yields * 0.1
print("yields_increased by 10% : \n", yields_increased)

yields_increased by 10% : 
 [[10. 20. 30. 40.]
 [50. 60. 70. 80.]
 [90. 50. 40. 30.]]


In [ ]:
yields_increased = yields_increased[0]
print("Only wheat's yield:\n", yields_increased)

Only wheat's yield:
 [10. 20. 30. 40.]


In [ ]:
avg_per_crop = np.mean(yields_increased, axis = 1)
print("Average yield per crop across all seasons:\n", avg_per_crop)

Average yield per crop across all seasons:
 [25.  65.  52.5]


In [ ]:
yields_increased = yields_increased[yields_increased > 30]
print("yields greater than 300:\n", yields_increased)

yields greater than 300:
 [40. 50. 60. 70. 80. 90. 50. 40.]


In [ ]:
#scenario : Factory Production Analaysis
import numpy as np

production = np.array([[3425, 3426, 7654, 5647], [2314, 2876, 5634, 9087], [3425, 3454, 7865, 4536]])

increased_production = production * 0.05
print("Production increased by 5%:\n", increased_production)

Production increased by 5%:
 [[171.25 171.3  382.7  282.35]
 [115.7  143.8  281.7  454.35]
 [171.25 172.7  393.25 226.8 ]]


In [ ]:
increased_production = increased_production[0]
print("Gadget's production:\n", increased_production)

Gadget's production:
 [171.25 171.3  382.7  282.35]


In [ ]:
avg_per_product = np.mean(increased_production, axis = 1)
print("Average production per product:\n", avg_per_product)

Average production per product:
 [251.9    248.8875 241.    ]


In [ ]:
increased_production = increased_production[increased_production > 50]
print("Values greater than 50:\n", increased_production)

Values greater than 50:
 [171.25 171.3  382.7  282.35 115.7  143.8  281.7  454.35 171.25 172.7
 393.25 226.8 ]


In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Salary": [60000, 70000, 80000]
}
df = pd.DataFrame(data)
df

,Name,Salary
0,A,60000
1,B,70000
2,C,80000


In [ ]:
type(df["Salary"])

pandas.core.series.Series